commercetools/sphere-node-product-csv-sync

src/coffee/mapping.coffee, src/spec/mapping.spec.coffee
=> Support set of money and number. Refs #74.

README.md, src/coffee/categories.coffee, src/coffee/constants.coffee, src/coffee/mapping.coffee, src/spec/categories.spec.coffee, src/spec/mapping.spec.coffee
@hajoeichler @emmenko Please check.
=> Categories by external

README.md, features/import.feature, package.json, src/coffee/import.coffee, src/coffee/queryutils.coffee, src/coffee/run.coffee, src/spec/queryutils.spec.coffee
__Questions__
Do we need to support another identifiers like `sku`?
If yes, how it supposed to make decision which one to use?
/cc @hajoeichler @emmenko
=> Batch input processing

.travis.yml, features/import.feature, src/coffee/export.coffee, src/coffee/import.coffee, src/coffee/run.coffee
Support reading input from `stdin`, redirect info messages to `stderr`, and allow writing output to `stdout`.
=> stdio support

src/coffee/export.coffee, src/coffee/exportmapping.coffee, src/coffee/run.coffee
=> Repeat product info in variants

.travis.yml, features/export.feature, features/import.feature, features/state.feature, src/coffee/helpers.coffee, src/coffee/import.coffee, src/coffee/matchutils.coffee, src/coffee/queryutils.coffee, src/coffee/validator.coffee, src/spec/import.spec.coffee, src/spec/integration/impex.spec.coffee, src/spec/integration/import.spec.coffee, src/spec/integration/state.spec.coffee, src/spec/mapping.spec.coffee, src/spec/matchutils.spec.coffee, src/spec/queryutils.spec.coffee, src/spec/validator.spec.coffee
=> [WIP] Match on import

package.json, src/coffee/run.coffee
=> Patch access token

src/coffee/constants.coffee, src/coffee/mapping.coffee, src/spec/integration/import.spec.coffee
@hajoeichler @emmenko I fixed the regex so that reimport of exported files, incl. discounted prices shouldn't be a problem anymore.
You can also check it here: https://regex101.com/r/kJ6oM0/1
Please review.
=> Change regex and mapping positions.

README.md, src/coffee/run.coffee
@hajoeichler @emmenko please review and new release please
=> support configuring protocols

src/coffee/exportmapping.coffee
@emmenko @hajoeichler plz review
bug was that categoryBy was "hard coded" to slug even if not provided
=> fix bug with categoryBy check

src/coffee/queryutils.coffee, src/spec/queryutils.spec.coffee
- add method to correctly format the predicate for custom attributes
- adapt tests accordingly
cc/ @hajoeichler @emmenko
=> Fix match by custom attributes

README.md, package.json, src/coffee/export.coffee, src/coffee/run.coffee, src/spec/integration/export.spec.coffee
This adds users possibility to specify output encoding of exported file.
Base branch is used that one with fullExport feature so we won't have conflicts later when merging to master
=> Export file encoding

src/coffee/exportmapping.coffee, src/spec/exportmapping.spec.coffee
=> Supports exports of set of ltext

data/moneySetAttributeProduct.json, data/moneySetAttributeProductType.json, src/coffee/exportmapping.coffee, src/spec/integration/export.spec.coffee, src/spec/integration/testhelpers.coffee
Fix of this issue https://github.com/sphereio/sphere-node-product-csv-sync/issues/126
=> fix(export): Mapping of money attributes

src/coffee/import.coffee, src/coffee/io/reader.coffee, src/coffee/run.coffee, src/coffee/validator.coffee, src/spec/integration/categoryOrderHint.spec.coffee, src/spec/integration/impex.spec.coffee, src/spec/integration/import.spec.coffee, src/spec/integration/importArchive.spec.coffee, src/spec/integration/importXlsx.spec.coffee, src/spec/integration/state.spec.coffee
This PR allows users to export data into excel XLSX format.
As it was in export-xlsx branch, I wanted to keep backward compatibility and do a refactor how the data are loaded but not so big changes because of small time capacity for this task and because it is getting quite urgent now.
Also note that this PR goes to export-xlsx branch so we can see only changes in import script
=> Import xlsx

Gruntfile.coffee, README.md, package.json, src/coffee/export.coffee, src/coffee/import.coffee, src/coffee/io/reader.coffee, src/coffee/io/writer.coffee, src/coffee/run.coffee, src/coffee/validator.coffee, src/spec/export.spec.coffee, src/spec/integration/categoryOrderHint.spec.coffee, src/spec/integration/export.spec.coffee, src/spec/integration/exportXlsx.spec.coffee, src/spec/integration/impex.spec.coffee, src/spec/integration/import.spec.coffee, src/spec/integration/importArchive.spec.coffee, src/spec/integration/importXlsx.spec.coffee, src/spec/integration/state.spec.coffee
This PR allows user to do a xlsx export.
=> Export xlsx files

README.md, data/moneySetAttributeProduct.json, src/coffee/constants.coffee, src/coffee/exportmapping.coffee, src/coffee/mapping.coffee, src/spec/exportmapping.spec.coffee, src/spec/integration/export.spec.coffee, src/spec/mapping.spec.coffee
=> Add price validity support to product export/import - Issue #150

README.md, src/coffee/export.coffee, src/coffee/run.coffee
=> refactor(export): Remove export as JSON parameter - Issue #139

src/coffee/import.coffee, src/spec/integration/importPublish.spec.coffee
=> Fix publishing after update when no actions are generated - Issue #165

src/coffee/queryutils.coffee, src/spec/integration/import.spec.coffee, src/spec/queryutils.spec.coffee
=> fix(query-utils): Escape double quotes from query

README.md
=> docs(import): Add info about importing localized fields

src/coffee/io/reader.coffee, src/coffee/validator.coffee, src/spec/reader.spec.coffee, src/spec/validator.spec.coffee
=> fix(csv): trim csv cells when parsing

package-lock.json, src/coffee/io/reader.coffee, src/spec/reader.spec.coffee
Fixes #187
This PR adds a stringify method for a richText object.
- Tests
=> fix(reader): Fix reading of xlsx richtext

src/spec/integration/import.spec.coffee, src/spec/integration/importPublish.spec.coffee, src/spec/integration/importXlsx.spec.coffee
=> chore(tests): make integration-tests work with updated prices

README.md
Small change to have the docs make more sense. Especially when building UIs like Impex.
=> docs(readme): update export categories description

package-lock.json, package.json, src/coffee/import.coffee
=> fix(product-update): support SameForAll attributes update

package-lock.json, src/coffee/import.coffee
`moveImageToPosition` action is misspelled [here](https://github.com/sphereio/sphere-node-product-csv-sync/blob/2e66af991a905938b9dc8f3094aa484a816cda26/src/coffee/import.coffee#L462)
PR updates this to correct spelling. 
- Tests
resolves #213
=> fix(import): fix misspelled action - moveImageToPosition

package-lock.json, src/coffee/export.coffee, src/coffee/exportmapping.coffee, src/spec/exportmapping.spec.coffee, src/spec/integration/export.spec.coffee
This PR adds a possibility to export products [state](https://docs.commercetools.com/http-api-projects-states.html#state) key.
Resolves #211 
- Tests
=> 211 exporting product state

README.md, package-lock.json, package.json, src/coffee/export.coffee, src/coffee/run.coffee, src/spec/integration/export.spec.coffee
This PR adds a new parameter which exports current product version instead of staged version
Resolves #217
- Tests
=> Add a new parameter which will export current version of products

src/coffee/mapping.coffee, src/spec/mapping.spec.coffee
Fixes #234 
This PR completes a missing mapping for `set of reference` and `set of boolean` attributes.
- Tests
=> fix(import-mapping): fix mapping of set of boolean and set of reference

src/coffee/constants.coffee, src/coffee/mapping.coffee, src/spec/mapping.spec.coffee
Fixes #236
Specify the whole list of attribute names which are being prefixed by the exporter.
- Tests
=> fix(mapping): fix mapping of prefixed attributes

package-lock.json, src/coffee/run.coffee
Fix  missing logging entries on product status during unpublish of products
This PR fixes missing log entries output when unpublish a large number of products in `Product Status` on IMPEX.
- Tests
Closes #249
=> fix(sphere-node-product-csv-sync): Logging entries missing on product status during unpublish of products

.travis.yml, package.json
=> chore: drop support for node v < 8

src/coffee/export.coffee
Fixes #245
The template command fails to pull in the project-key.
Tests pass when adding a config.js file, not sure what to reference there
=> Fix exporting of template due to missing credentials

README.md, src/coffee/categories.coffee, src/coffee/mapping.coffee, src/spec/categories.spec.coffee
externalId
namedPath
name
key
Fixes: #247
=> feat(product-import): add support for category key

README.md
=> add documentation for labels and dimension for each image

README.md, src/coffee/import.coffee, src/coffee/run.coffee
--noStaged will be used if user want to publish only the changes given
to the input file not any other stage changes.
Fixes: #283
=> feat(product-import): Add support for noStaged flag

Gruntfile.coffee
=> release Enable test for next release

package-lock.json, package.json
=> fix(deps): Remove github vulneribility warnings

.travis.yml, Gruntfile.coffee, src/spec/integration/categoryOrderHint.spec.coffee, src/spec/integration/import.spec.coffee, src/spec/integration/testhelpers.coffee
Cucumber test cases looks like very fragile and breaking a lot because of version modification which is hard to tracked.
Removed node 10 because when test runs in parallel our test cases breaks because they share the same project.
coveralls.js is failing because we moved our project from one project to another so removed for time being.
Fix: #311
=> Fix pipeline issues

src/coffee/mapping.coffee
Fix: https://github.com/commercetools/express-impex/issues/763
=> fix: same for all attribute
